### ISSUE TITLE
Incompatible shapes

### ISSUE THREAD

**Issue by BauTobias93** [emadboctorx/yolo-tf2#16]
Hi,
my problem is regarding incompatible shapes in some layer while training on a custom dataset. The custom dataset is rather small but will be expanded soon, so I wanted to check first if it runs on the small size: 3851 frames of a short video (used as single images for training) with only 2 classes and 9163 labels

**My error message:**
```
Traceback (most recent call last):
  File "YOLO_train.py", line 24, in <module>
    trainer.train(
  File "C:\Users\P42412\Documents\yolotf2\yolov3-keras-tf2\yolo_tf2\utils\common.py", line 62, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\P42412\Documents\yolotf2\yolov3-keras-tf2\yolo_tf2\core\trainer.py", line 532, in train
    history = self.training_model.fit(
  File "C:\Users\P42412\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\P42412\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "C:\Users\P42412\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\P42412\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "C:\Users\P42412\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "C:\Users\P42412\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "C:\Users\P42412\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "C:\Users\P42412\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\function.py", line 545, in call
    outputs = execute.execute(
  File "C:\Users\P42412\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [8,5,5,3,1] vs. [8,20,20,3,1]
         [[node yolo_loss_2/logistic_loss/mul (defined at C:\Users\P42412\Documents\yolotf2\yolov3-keras-tf2\yolo_tf2\utils\common.py:232) ]] [Op:__inference_train_function_25976]

Errors may have originated from an input operation.
Input Source operations connected to node yolo_loss_2/logistic_loss/mul:
 yolo_loss_2/split_1 (defined at C:\Users\P42412\Documents\yolotf2\yolov3-keras-tf2\yolo_tf2\utils\common.py:202)
 yolo_loss_2/split (defined at C:\Users\P42412\Documents\yolotf2\yolov3-keras-tf2\yolo_tf2\utils\common.py:180)

Function call stack:
train_function
```

**My setup:**
```
from yolo_tf2.core.trainer import Trainer
trainer = Trainer(
         input_shape=(160, 160, 3),
         model_configuration='C:/Users/P42412/Documents/yolotf2/yolov3-keras-tf2/yolo_tf2/config/yolo3.cfg',
         classes_file='C:/Users/P42412/Documents/yolotf2/classes.txt',
         image_width=640,  # The original image width
         image_height=480   # The original image height
)

dataset_conf = {
              'relative_labels': 'C:/Users/P42412/Documents/yolotf2/labels.csv',
              'dataset_name': 'tennis_1',
              'test_size': 0.2,
              'augmentation': False,
}
anchors_conf = {
                'anchor_no': 9,
                'relative_labels':  'C:/Users/P42412/Documents/yolotf2/labels.csv'
}

trainer.train(
         epochs=100, 
         batch_size=8, 
         learning_rate=1e-3, 
         dataset_name='tennis_1', 
         merge_evaluation=False,
         min_overlaps=0.5,
         new_dataset_conf=dataset_conf,  # check step 5
         new_anchors_conf=anchors_conf,  # check step 6
         #  weights='/path/to/weights'  # If you're using DarkNet weights or resuming training
         )

```

I tried different input shapes, but this did not solve my problem. Also another question, does the input size have to be a square?

Thank you in advance for your answer!

**Comment by emadboctorx** [comment]
I got this error before which turned out to be a problem with the dataset labels, when I checked there were coordinates that were out of bounds ex: image width and height are 1344, 756 respectively and there are coordinates that are pointing to 1588, 888 so it produced the very same error above. I suggest you test with 2-3 examples max and start training, most probably the problem will be gone, then next you'll have to check the dataset for sources of the problem. Regarding the input shapes, please stick to the defaults that are present in the DarkNet cfg file (416, 416, 3 or 608, 608, 3 for yolo3 and yolo4 respectively). Also regarding the anchors, I usually get better results with the default ones, so no need to specify `anchors_conf` unless you have a good reason to.

**Comment by BauTobias93** [comment]
Thank you for your help and quick answer. Also, sorry that it took me so long to get back to this project.

I used your suggestions and changed the input shapes back to the default `416,416` and also using the default `anchors_conf`. I also checked my dataset, but all relative coordinates are inside the boundries and seem fine to me.
When using the different configurations, I was able to train a model with 3 images without any errors (after severall trys because sometimes I ran in the NaN problem, explained underneath).

When I want to increase the training dataset (1,000 images), I run into either one of two problems:

- batch_size > 2: 
```
OOM when allocating tensor with shape[4,512,26,26] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
[[node gradient_tape/functional_1/layer_229_conv2d/Conv2D/Conv2DBackpropInput
```
I guess, I will need a better graphic card with more RAM to be able to train it with this configurations.
- batch_size <= 2:
```
     27/Unknown - 38s 1s/step - loss: nan - layer_205_lambda_loss: nan - layer_230_lambda_loss: nan - layer_255_lambda_loss: nan
     28/Unknown - 39s 1s/step - loss: nan - layer_205_lambda_loss: nan - layer_230_lambda_loss: nan - layer_255_lambda_loss: nan
     29/Unknown - 41s 1s/step - loss: nan - layer_205_lambda_loss: nan - layer_230_lambda_loss: nan - layer_255_lambda_loss: nan
     30/Unknown - 42s 1s/step - loss: nan - layer_205_lambda_loss: nan - layer_230_lambda_loss: nan - layer_255_lambda_loss: nan
``` 
Why is there a NaN value as a lambda_loss value? Aren´t there supposed to be real valued numbers? I guess there is a problem since NaN are no number values and can not be processed/improved.
Training does finish but the model is not able to do even one prediction.

Can you help me with this? Any suggestions?

**Comment by emadboctorx** [comment]
Yes, the OOM is a result of limited memory, regarding the `nan` values, you said that you were able to train a model successfully without errors / problems and then you got this problem in your most recent trial, so check what changes you have made, in order to identify the source of the issue. `Nan` values are sometimes the result of a learning rate being higher than it should, however could be any other problem with the dataset, so try lowering the learning rate, check for differences between both good / problematic outcomes and let me know.

**Comment by BauTobias93** [comment]
Thank you for your quick response. I can´t figure out what is going wrong. I tried many different parameter changes (learning rate, batch size) and looked at the data carefully but I am not able to see the problem.

Would you mind trying to run your script on your setup with a small data sample of mine? 
I did put 11 images with 2 classes and labels in the zip file and a python file with my setup (but with absolute paths). This would help me a lot to identify if it is a problem of my hardware setup or something else. I tried the same script with same framework versions (as in `requirement.txt`) on different computers and got different problems, one has the `input shape error`, the other one is not able to train the model with the `NaN lambda loss function` calculation.

[dataset_bautobias93.zip](https://github.com/emadboctorx/yolo-tf2/files/5560664/dataset_bautobias93.zip)

**Comment by emadboctorx** [comment]
@BauTobias93 has the issue been resolved?

**Comment by BauTobias93** [comment]
I fixed the `NaN values` issue by correcting a typo in the classfile (I am an idiot!). Usually this is generated by a previous step of mine but somehow I wrote that by hand for my 2 classes and this screwed everything up somehow allthough the object ids were correct.
I am able to train a NN with batch_size 1 on my notebooks successfully.

Now I wanted to use the same script with the same versions on a different computer with more GPU-RAM and I got the `Incompatible shapes` error from my original comment again. Now I actually know what fixed this error the first time, it was the change of my workstation from my computer to my notebook.
I run my projects in VS2019 and they have a feature which creates an environment based on the requirement.txt file, so I know I use the same versions on both computers, specified in the file. Besides that I made sure that I actually copied the same datafile (and project) as used on my notebook to make sure there is not another typo or similar.

I deactivated the GPU on my notebook and my computer (with `os.environ["CUDA_VISIBLE_DEVICES"] = "-1"`) to check if this is an issue because of the different graphic cards, but my notebook was still able to train and my computer got the same shape error.

I tried to debugg the whole thing but this is just a mess, and I can´t figure out what is important to look at to find the problem. 

Do you have any idea what could cause this error on a different PC?
I will check the data, the versions of the packages and the project another time...

**Comment by emadboctorx** [comment]
There's not enough information to answer your questions correctly, there can be a dozen reasons ranging from you overlooking something that is present / is missing in one of the pcs, incompatible package versions, a forgotten step ... and generally it's cleaner if you install the project in a virtual environment rather than globally in order minimize conflicts with system packages (if any). And please do not install the project using `pip` but use `python setup.py install` and use the command line interface because it minimizes implementation details you don't have to deal with and possibly overlook / miss a step in between. Most probably it's a system specific issue or you overlooking something but could be another thing as well, can't guarantee that this is the case.

**Comment by emadboctorx** [comment]
@BauTobias93 please check the recent update and let me know if the changes fixed your issue.

**Comment by emadboctorx** [comment]
I closed this issue as it have stalled, feel free to re-open it when you need to
