### ISSUE TITLE
Wrong anchors

### ISSUE THREAD

**Issue by mattangus** [emadboctorx/yolo-tf2#18]
I tried running yolov4 weights and config from `alexyab`, but it seems like there is something wrong with the anchors. Here is an example of detections.

![image](https://user-images.githubusercontent.com/5302804/100364700-618ca680-2ff6-11eb-9f25-906c31b2bebb.png)

The predictions seem good but the anchors might be wrong. I haven't changed the code:

```
        self.version_anchors = {
            'v3': np.array(
                [
                    (10, 13),
                    (16, 30),
                    (33, 23),
                    (30, 61),
                    (62, 45),
                    (59, 119),
                    (116, 90),
                    (156, 198),
                    (373, 326),
                ],
                np.float32,
            ),
            'v4': np.array(
                [
                    (12, 16),
                    (19, 36),
                    (40, 28),
                    (36, 75),
                    (76, 55),
                    (72, 146),
                    (142, 110),
                    (192, 243),
                    (459, 401),
                ]
            ),
        }
```

and the anchors of the cfg file:

```
12.0,16.0,19.0,36.0,40.0,28.0,36.0,75.0,76.0,55.0,72.0,146.0,142.0,110.0,192.0,243.0,459.0,401.0
```

Any idea what is going on here?

**Comment by mattangus** [comment]
The command I use is:

```
python3 yolo_tf2/cli.py detect --video vid.mp4 --weights yolov4.weights --input-shape "(608, 608, 3)" --model-cfg yolov4.cfg  --classes coco.names --display-vid
```

**Comment by mattangus** [comment]
I can confirm that it is an anchor issue. For this particular detection I can fix it by changing the anchors with `np.roll(anchors, -6, 0)`. `-6` was from manually testing it. This single detecion is fixed but the other are not.

**Comment by emadboctorx** [comment]
Does the issue occur on images too? Try detecting images instead of a video and see if the problem persists and if it does, include the steps you followed. These anchors are the same anchors used by Alexey, they shouldn't be a problem. I tested the code on multiple platforms using the same anchors and they work just fine, so I don't think it's the anchors but this is not necessarily true. A side note, you may install the project using `python setup.py install` and you may then use `yolotf2 do-stuff` instead of calling `cli.py` module, it has nothing to do with the issue though.

**Comment by mattangus** [comment]
Yes, it seems to happen with running on an image too:

```
python3 yolo_tf2/cli.py detect --image images.jpeg --weights yolov4.weights --input-shape "(608, 608, 3)" --model-cfg yolov4.cfg  --classes coco.names --output-dir outdir/
```
Here is the output:

![images](https://user-images.githubusercontent.com/5302804/100435703-38235780-3096-11eb-91f2-c158739adb15.jpeg)

Maybe it's a tensorflow version thing. I'm running 2.2, i'll try 2.3 (like in requirements.txt).

**Comment by mattangus** [comment]
Same issue, in a docker container `nvidia-docker run -it -v $(pwd):/workspace nvidia/cuda:9.2-cudnn7-devel-ubuntu18.04 /bin/bash` with everything installed via `requirements.txt`

**Comment by mattangus** [comment]
I just re-downloaded the weights from [darknet repo](https://github.com/AlexeyAB/darknet/wiki/YOLOv4-model-zoo) and same thing.

**Comment by mattangus** [comment]
I've found the issue. It seems to be a yolov4 problem. I ran it with V3 and no problem:

![images](https://user-images.githubusercontent.com/5302804/100440124-4c6a5300-309c-11eb-84b0-0677a9d04a02.jpeg)

**Comment by mattangus** [comment]
These are the commands I run to reproduce:

```bash
nvidia-docker run -it nvidia/cuda:9.2-cudnn7-devel-ubuntu18.04 /bin/bash
# now inside the container
apt update
apt install -y python3.8-dev wget git python3.8-distutils
wget https://bootstrap.pypa.io/get-pip.py
python3.8 get-pip.py
git clone https://github.com/emadboctorx/yolo-tf2.git
cd yolo-tf2/
python3.8 -m pip install -r requirements.txt
export PYTHONPATH=$(pwd) # this is needed for some reason
mkdir outdir
wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights
wget https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4.cfg
wget https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/coco.names
wget https://www.statnews.com/wp-content/uploads/2020/08/GettyImages-1227214507-768x432.jpg -O images.jpeg
python3.8 yolo_tf2/cli.py detect --image images.jpeg --weights yolov4.weights --input-shape "(608, 608, 3)" --model-cfg yolov4.cfg  --classes coco.names --output-dir outdir/
# copy image. run outside of container. `docker ps` is used to get <container id>
docker cp <container id>:/yolo-tf2/outdir/images.jpeg temp.jpeg
```

**Comment by emadboctorx** [comment]
@mattangus okay, the problem is not with the anchors, please comment out those 2 lines in yolo_tf2 > core > models.py lines 427, 428

        if '4' in self.model_configuration:
            self.output_layers.reverse()

This is a temporary fix, It will work correctly for detection for now (not for training) until I find a workaround to get rid of these 2 lines

**Comment by mattangus** [comment]
That did the trick! Thanks for your effort :smile:
