### ISSUE TITLE
Can't verify installation

### ISSUE THREAD

**Issue by marireeves** [emadboctorx/yolo-tf2#19]
Hi There - I'm trying to use this object detector (thank you so much for putting it together), but I can't verify the installation. I get through all the requirements in the README.me doc in the repo (pulled 1/5/2021) but when I get to the verify installation step, it gives me a "command not found" error. 

I'm pretty new to linux in the terminal, and did get a few GPU warnings on the install, but don't think that's causing it because the detct.py demo script will run (and will run on one of my photos, too). 

Any chance you have insight into why this error is occurring? I'm on a Microsoft Azure Data Science Virtual Machine running  Ubuntu 18.04 Standard NC6_Promo (6 vcpus, 56 GiB memory)..via SSH connection through Putty to a windows 10 laptop. I am working only in the terminal and have not been able to set up a graphics enabled user interface on the VM yet.

Here is the install record then the error.  Thanks for the help!

yolotf2: command not found
(yolov3-tf2-gpu) Booby@FindTheBirdsUbuntu:~/yolov3-tf2$ python setup.py install
running install
running bdist_egg
running egg_info
writing yolov3_tf2.egg-info/PKG-INFO
writing dependency_links to yolov3_tf2.egg-info/dependency_links.txt
writing top-level names to yolov3_tf2.egg-info/top_level.txt
reading manifest file 'yolov3_tf2.egg-info/SOURCES.txt'
writing manifest file 'yolov3_tf2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/yolov3_tf2
copying build/lib/yolov3_tf2/__init__.py -> build/bdist.linux-x86_64/egg/yolov3_tf2
copying build/lib/yolov3_tf2/models.py -> build/bdist.linux-x86_64/egg/yolov3_tf2
copying build/lib/yolov3_tf2/utils.py -> build/bdist.linux-x86_64/egg/yolov3_tf2
copying build/lib/yolov3_tf2/dataset.py -> build/bdist.linux-x86_64/egg/yolov3_tf2
byte-compiling build/bdist.linux-x86_64/egg/yolov3_tf2/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/yolov3_tf2/models.py to models.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/yolov3_tf2/utils.py to utils.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/yolov3_tf2/dataset.py to dataset.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying yolov3_tf2.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying yolov3_tf2.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying yolov3_tf2.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying yolov3_tf2.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/yolov3_tf2-0.1-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing yolov3_tf2-0.1-py3.7.egg
Copying yolov3_tf2-0.1-py3.7.egg to /anaconda/envs/yolov3-tf2-gpu/lib/python3.7/site-packages
Removing yolov3-tf2 0.1 from easy-install.pth file
Adding yolov3-tf2 0.1 to easy-install.pth file

Installed /anaconda/envs/yolov3-tf2-gpu/lib/python3.7/site-packages/yolov3_tf2-0.1-py3.7.egg
Processing dependencies for yolov3-tf2==0.1
Finished processing dependencies for yolov3-tf2==0.1
(yolov3-tf2-gpu) Booby@FindTheBirdsUbuntu:~/yolov3-tf2$ yolotf2
yolotf2: command not found

**Comment by emadboctorx** [comment]
The installation is finished successfully according to what the log indicates, it should work. Anyway please follow the installation steps I followed in this [notebook](https://colab.research.google.com/drive/1NWKwbFx6BeDkY1-O5zk96Xz-5t4jpp_Q?usp=sharing) it should work. If it doesn't, try installing in a virtualenv using `pip install .` from within the repo's dir

**Comment by emadboctorx** [comment]
After going through the log you provided again, I noticed that you're trying to install an outdated version which did not have command line options support. Please clone a fresh copy of the repo or use `git pull origin master` and then reinstall, and if the issue persists, feel free to re-open the issue.

**Comment by marireeves** [comment]
Iʻll go through the notebook, but these were the messages I received. Based on your message, I didnʻt believe it was up to date, so tried to pull from https, and got the second message. 

(yolov3-tf2-gpu) Booby@FindTheBirdsUbuntu:~/yolov3-tf2$ git pull origin master
From https://github.com/zzh8829/yolov3-tf2
 * branch            master     -> FETCH_HEAD
Already up to date.


(yolov3-tf2-gpu) Booby@FindTheBirdsUbuntu:~/yolov3-tf2$ git pull https://github.com/emadboctorx/yolo-tf2
warning: no common commits
remote: Enumerating objects: 67, done.
remote: Counting objects: 100% (67/67), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 1015 (delta 33), reused 47 (delta 23), pack-reused 948
Receiving objects: 100% (1015/1015), 14.49 MiB | 18.54 MiB/s, done.
Resolving deltas: 100% (653/653), done.
From https://github.com/emadboctorx/yolo-tf2
 * branch            HEAD       -> FETCH_HEAD
fatal: refusing to merge unrelated histories
(yolov3-tf2-gpu) Booby@FindTheBirdsUbuntu:~/yolov3-tf2$

**Comment by marireeves** [comment]
Iʻm going to go with this, and follow your notebook. Iʻll let you know how it goes. https://www.educative.io/edpresso/the-fatal-refusing-to-merge-unrelated-histories-git-error

**Comment by emadboctorx** [comment]
Just delete you local version and clone a fresh one, you don't need to worry about these things.

**Comment by marireeves** [comment]
Using your notebook install, it worked. https://colab.research.google.com/drive/1NWKwbFx6BeDkY1-O5zk96Xz-5t4jpp_Q?usp=sharing#scrollTo=ZM3YDjTX0CDT
Thanks!

**Comment by emadboctorx** [comment]
You're welcome, and let me know if you encounter any other issues.
