### ISSUE TITLE
Input resolution

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [emadboctorx/yolo-tf2#21]
I tried to feed different resolution inputs and found the following issues
1. Looks like while augmenting, it is expecting to have a single resolution from all the input samples
2. while training also, it is giving an error if the input resolution is different as follows
"""  File "/home/veeru/anaconda3/envs/tf_fish_2.4/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Cannot batch tensors with different shapes in component 0. First element had shape [2058,2448,3] and element 3 had shape [1029,1224,3].
	 [[node IteratorGetNext (defined at /lib/python3.8/site-packages/yolo_tf2/core/trainer.py:530) ]]
  (1) Cancelled:  Function was cancelled before it was started
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_34607]

Function call stack:
train_function -> train_function"""

So do we need to pass all the images which are in same resolution?

**Comment by emadboctorx** [comment]
Yes, for the current version to work, you need to provide images of the same dimensions.
