### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [emadboctorx/yolo-tf2#24]
Hi,
I was trying to use your augmentation guide as shown below in readme and there is typo as mentioned

from yolo_tf2.config.augmentation_options import augmentations
from yolo_tf2.core.augmentor import DataAugment

aug = DataAugment(
      labels_file='/path/to/labels/csv/file',
      augmentation_map=augmentations)
aug.create_sequences(sequences)  # check the docs
aug.augment_photo_folder() ### this is wrong
**aug.augment_photos_folder()**

**Comment by emadboctorx** [comment]
Thanks, I'll fix it in the next update.
