### ISSUE TITLE
Number of Anchor boxes MUST be 9?

### ISSUE THREAD

**Issue by maurimarco** [emadboctorx/yolo-tf2#30]
I'm trying to train with my own dataset
Is it possible to change the number of Anchor boxes in anchors_conf? (from 9 to, for instance, 3.)

ps
The Anchor boxes detection algorithm fails to find 9 different boxes with my dataset. With 3 is fine, but the train fails....

**Comment by emadboctorx** [comment]
> but the train fails....

Please check the [issue policy](https://github.com/emadboctorx/yolo-tf2#issue-policy) and provide the missing details, in order for me to be able to help you. And yes, you can use any number of anchors as long as it is a multiple of 3 by passing `anchors=your_anchors`.

**Comment by maurimarco** [comment]
Here's some more details and some info I got debugging:
I set:

`'anchor_no': 9` 

And running a training with custom dataset the code enters an infinite loop.
Here's a sample of the output:

2021-07-12 14:05:44,080 yolo_tf2.utils.common.train +467: INFO     [8620] Starting training ...
2021-07-12 14:05:44,080 yolo_tf2.utils.common.train +469: INFO     [8620] Generating new anchors ...
2021-07-12 14:05:44,087 yolo_tf2.utils.common.parse_voc_folder +105: INFO     [8620] Labels retrieved from cache:
Pin    723
Name: object_name, dtype: int64
Iteration: 0 Loss: 795.391238007916
C:\Users\<username>\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\fromnumeric.py:3372: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\<username>\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\_methods.py:162: RuntimeWarning: invalid value encountered in true_divide
  ret = um.true_divide(
Iteration: 1 Loss: nan
Iteration: 2 Loss: nan
Iteration: 3 Loss: nan
Iteration: 4 Loss: nan
Iteration: 5 Loss: nan
Iteration: 6 Loss: nan
Iteration: 7 Loss: nan
Iteration: 8 Loss: nan
Iteration: 9 Loss: nan

And it goes on like this.


Here's my guess:
In  **anchors.py**,  in the function` k_means`, `centroids[anchor]` can become `[nan, nan]` if the condition `current_nearest == anchor` is never satisfied. 

If I understand correctly things get messy if a given centroid has no closest points.

**Comment by emadboctorx** [comment]
What are the inputs of `yolo_tf2.utils.anchors.k_means`?

**Comment by maurimarco** [comment]
I cannot provide a colab notebook at the moment, but I've prepared a short python script to reproduce the issue:

[k_means_test.zip](https://github.com/emadboctorx/yolo-tf2/files/6807143/k_means_test.zip)

The data are the one actually coming from my dataset.

**Comment by emadboctorx** [comment]
I think there may be a problem with the dataset labels because the values in the example you provided are all close to (0.003, 0.73) respectively. This either indicates you only have one class and all the examples are more or less identical, in which case, you can't have more than one cluster or `k = 1`. Which won't work with the implementation which expects `k` to be a multiple of 3, and then you'll have to stick with the default anchors.  And this can be proved by setting `k = 1` in `k_means()`, the code should work fine:

    anchor_boxes = 1
    k_means(my_relative_sizes,anchor_boxes)

Out:

    Iteration: 0 Loss: 78.64291204125044
    
    Process finished with exit code 0

If this is not the case, and you have multiple classes and you expect the bounding boxes in the examples should have different areas, then you'll have to verify the coordinates in your dataset.

**Comment by maurimarco** [comment]
I have a single class and the bounding boxes are pretty close to each others, you are right.
I'll close the issue.
