### ISSUE TITLE
cannot  start train on  XML VOC format

### ISSUE THREAD

**Issue by laplace674** [emadboctorx/yolo-tf2#9]
I try to use  XML VOC format to train my own data.  I have already followed your step, but always raise the following issue
![image](https://user-images.githubusercontent.com/32185996/88792746-518ec280-d1ce-11ea-9a1f-a2c08ccec965.png)

could you help?

**Comment by emadboctorx** [comment]
Did you specify in `new_dataset_conf` `from_xml: True`? If yes, can you reply with the steps you followed that resulted in the issue? I can't replicate the issue without checking what you did.

**Comment by emadboctorx** [comment]
I closed this issue as it has stalled, feel free to re-open it when you need to
